version: "3"

services:
  db:
    image: postgres
    restart: always
    container_name: postgres-container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=database
      - POSTGRES_PASSWORD=database
      - POSTGRES_DB=database